name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run unittest test
        run: id

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run integration test
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
          USERNAME: ${{ secrets.USERNAME }}
        with: 
          name: dist
      - shell: bash
        run: chmod u+x build/quick-test.sh && bash build/quick-test.sh
             exit $?
 
  deploy:
    runs-on: ubuntu-latest
    needs: [unittest, integration_test]
    steps:
      - uses: actions/checkout@v3
      - name: build and publish image
        run: ls -al
