name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CR_PAT: ${{ secrets.CR_PAT }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run end2end test
        env: 
          TEST_DATABASE: ${{ secrets.TEST_DATABASE }}
        run: chmod u+x build/quick-test.sh && build/quick-test.sh
             exit $?
