name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CR_PAT: ${{ secrets.CR_PAT }}
  USERNAME: ${{ secrets.USERNAME }}
  TEST_DATABASE: ${{ secrets.TEST_DATABASE }}

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: compile modules
        run: |
          chmod u+x build/build.sh 
          build/build.sh -c iengine
          build/build.sh -c manager
          build/build.sh -c plugin-kit
          build/build.sh -c connectors
      - name: package module
        run: build/build.sh -p 1 -o image
      - name: run unittest
        run: ls -al
      - name: run integrate test
        run: chmod u+x build/quick-test.sh && build/quick-test.sh
             exit $?
