name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: run end2end test
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: build/quick-test.sh
